# Generated by Django 5.2.12 on 2026-03-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='member_answer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='member_answer'),
        ),
    ]
